import { ArrowLeft, ArrowUpRight, BarChart3, CalendarDays, CheckCircle2, LayoutGrid, Link2, List, MousePointer2, UsersRound } from "lucide-react";
import { Link } from "wouter";
import { useState } from "react";
import WorkspaceShell from "@/components/WorkspaceShell";
import { useCurrency } from "@/lib/currency";

const acceptedCampaigns = [
  { slug: "loop-finance", advertiser: "Loop Finance", title: "Build a calmer money routine", community: "After Hours", platform: "Discord", link: "relay.to/go/after-hours/campaign-4821", clicks: "284", visitors: "231", earnings: 1200, remaining: "12 days", deadline: "Jul 04", tone: "lilac" },
  { slug: "moss-market", advertiser: "Moss Market", title: "Weekend plans, made easier", community: "Sunday Selects", platform: "WhatsApp", link: "relay.to/go/sunday-selects/campaign-4822", clicks: "167", visitors: "139", earnings: 720, remaining: "18 days", deadline: "Jul 11", tone: "moss" },
  { slug: "studio-notes", advertiser: "Studio Notes", title: "A better creative workflow", community: "Design Dispatch", platform: "Telegram", link: "relay.to/go/design-dispatch/campaign-4823", clicks: "96", visitors: "82", earnings: 540, remaining: "21 days", deadline: "Jul 22", tone: "coral" },
];

export default function AcceptedCampaigns() {
  const { format } = useCurrency();
  const currencyLabel = format(0).split(" ")[0];
  const [view, setView] = useState<"list" | "cards">("list");
  return <WorkspaceShell active="Campaigns"><div className="dashboard-body accepted-page"><Link className="hero-link route-back-link" href="/campaigns"><ArrowLeft size={15} /> Back to campaigns</Link><section className="route-page-heading accepted-page-heading"><div><span className="section-kicker"><span className="section-kicker-line" /> Campaign tracking</span><h1>Accepted campaigns</h1><p>Open a campaign to copy its tracking link, post the approved ad, and follow results for that community.</p></div><div className="accepted-page-summary"><strong>{acceptedCampaigns.length}</strong><span>active campaigns</span></div></section><div className="accepted-page-note"><Link2 size={16} /><span>Every campaign has its own link connected to the advertiser, campaign, community, and you as the owner.</span></div><div className="accepted-view-toolbar"><div><strong>Your active campaigns</strong><span>{acceptedCampaigns.length} campaigns</span></div><div className="accepted-view-toggle" role="group" aria-label="Change campaign view"><button className={view === "list" ? "accepted-view-active" : ""} onClick={() => setView("list")} aria-label="List view"><List size={15} /> List</button><button className={view === "cards" ? "accepted-view-active" : ""} onClick={() => setView("cards")} aria-label="Card view"><LayoutGrid size={15} /> Cards</button></div></div><section className={`accepted-campaign-grid ${view === "list" ? "accepted-campaign-list-view" : "accepted-campaign-cards-view"}`}>{acceptedCampaigns.map((campaign) => <article className={`accepted-campaign-card accepted-campaign-card-${campaign.tone}`} key={campaign.slug}><div className="accepted-card-top"><div><span className="accepted-card-status"><span /> Active</span><h2>{campaign.title}</h2><p>{campaign.advertiser} · {campaign.community} · {campaign.platform}</p></div><span className="accepted-card-icon"><BarChart3 size={18} /></span></div><div className="accepted-card-link"><small>Tracking link</small><code>{campaign.link}</code></div><div className="accepted-card-stats"><span><MousePointer2 size={14} /><strong>{campaign.clicks}</strong><small>clicks</small></span><span><UsersRound size={14} /><strong>{campaign.visitors}</strong><small>visitors</small></span><span><span className="metric-currency">{currencyLabel}</span><strong>{format(campaign.earnings, 0).replace(`${currencyLabel} `, "")}</strong><small>earned</small></span></div><div className="accepted-card-footer"><span><CalendarDays size={13} /> {campaign.remaining} · Ends {campaign.deadline}</span><Link href={`/campaigns/${campaign.slug}/workspace`} className="accepted-workspace-button">Open campaign <ArrowUpRight size={15} /></Link></div></article>)}</section><div className="accepted-page-footer"><CheckCircle2 size={15} /> Clicks are counted only when someone opens your tracked destination after leaving their community app.</div></div></WorkspaceShell>;
}
