import { ArrowLeft, ArrowRight, Eye, EyeOff, LockKeyhole, Mail, ShieldCheck } from "lucide-react";
import { FormEvent, useState } from "react";
import { Link, useLocation } from "wouter";
import { loginRelayAccount, relayBackendEnabled } from "@/lib/relayApi";

export default function LoginPage() {
  const [location, setLocation] = useLocation(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [showPassword, setShowPassword] = useState(false); const [error, setError] = useState("");
  const query = new URLSearchParams(location.split("?")[1] ?? ""); const notice = query.get("verified") ? "Email verified. You can now sign in." : query.get("reset") ? "Password reset successfully. Please sign in." : "";
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(""); if (!email.includes("@") || password.length < 6) { setError("Enter a valid email and a password with at least 6 characters."); return; } if (relayBackendEnabled()) { try { const user = await loginRelayAccount(email, password); sessionStorage.setItem("relay_signup_email", user.email); sessionStorage.setItem("relay_signup_name", user.displayName); sessionStorage.setItem("relay_signup_role", user.role === "CommunityOwner" ? "community-owner" : "advertiser"); setLocation(user.role === "CommunityOwner" ? "/community-owner" : "/campaign-owner"); return; } catch { setError("Relay could not sign you in. Check your credentials or disable backend mode for the local demo."); return; } } const role = sessionStorage.getItem("relay_signup_role") ?? "advertiser"; setLocation(role === "community-owner" ? "/community-owner" : "/campaign-owner"); };
  return <AuthShell eyebrow="Welcome back" title="Sign in to your marketplace." text="Pick up where you left off with your campaigns, communities, and qualified-click results."><form className="auth-form" onSubmit={submit}>{notice && <p className="auth-inline-notice"><ShieldCheck size={14} />{notice}</p>}<label>Email address<div className="auth-input"><Mail size={16} /><input type="email" value={email} onChange={event => setEmail(event.target.value)} placeholder="you@company.com" /></div></label><label>Password<div className="auth-input"><LockKeyhole size={16} /><input type={showPassword ? "text" : "password"} value={password} onChange={event => setPassword(event.target.value)} placeholder="Enter your password" /><button type="button" aria-label={showPassword ? "Hide password" : "Show password"} onClick={() => setShowPassword(!showPassword)}>{showPassword ? <EyeOff size={16} /> : <Eye size={16} />}</button></div></label><div className="auth-form-row"><label className="auth-check"><input type="checkbox" /> <span>Remember me</span></label><Link href="/forgot-password" className="auth-forgot">Forgot password?</Link></div>{error && <p className="auth-error">{error}</p>}<button className="auth-submit" type="submit">Sign In <ArrowRight size={16} /></button><p className="auth-switch">Don't have an account? <Link href="/register">Create one</Link></p></form></AuthShell>;
}
function AuthShell({ eyebrow, title, text, children }: { eyebrow: string; title: string; text: string; children: React.ReactNode }) { return <div className="auth-page"><div className="auth-brand-panel">
  
  
  
  
  
  <Link href="/" className="public-brand"><span className="public-brand-mark"><i /><i /><i /></span>relay</Link><div className="auth-brand-copy"><span className="public-eyebrow"><span /> {eyebrow}</span><h1>Qualified attention<br /><em>starts here.</em></h1><p>Connect campaigns to communities where people already care.</p><div className="auth-brand-detail"><span><ShieldCheck size={15} /> Trusted community placements</span><span><ArrowRight size={15} /> Measurable CPC results</span></div></div></div><main className="auth-form-panel"><div className="auth-form-wrap"><span className="public-eyebrow public-eyebrow-dark"><span /> {eyebrow}</span><h2>{title}</h2><p>{text}</p>{children}</div></main></div>; }
