import { ArrowLeft, ArrowRight, ShieldCheck } from "lucide-react";
import { Link } from "wouter";

const sections = [
  { title: "Information collected", body: ["We collect information you provide when you create an account, set up a profile, create or apply to a campaign, contact us, or otherwise use the marketplace. We also collect limited technical information needed to operate and protect the service."] },
  { title: "Account and profile information", body: ["Depending on your role, this may include your name, email address, password-related account details, business or community profile information, location, and preferences. We use this information to create your workspace, communicate with you, and show relevant marketplace opportunities.", "Do not include sensitive personal information in public profile fields or campaign content unless it is necessary for your use of the marketplace."] },
  { title: "Community and campaign information", body: ["Advertisers may provide campaign names, descriptions, budgets, CPC settings, audience criteria, destinations, and approved advertisements. Community Owners may provide community names, platforms, audience sizes, categories, locations, and placement information.", "Some profile and campaign details may be visible to the other side of a marketplace transaction when needed to evaluate a campaign, community, application, or placement."] },
  { title: "Tracking links and click data", body: ["The marketplace uses unique tracking links to attribute qualified traffic to an accepted placement. When a visitor follows one of these links, we may record the tracking identifier, time of the event, destination, and limited technical signals used to detect duplicates, abuse, or invalid activity.", "Click data is used to calculate campaign performance, advertiser spend, and Community Owner earnings. We do not use tracking links to collect the contents of private conversations or to read a community's member messages."] },
  { title: "How information is used", body: ["We use information to provide and improve the marketplace; operate advertiser and Community Owner workspaces; match campaigns with relevant communities; process applications and placements; calculate qualified clicks, CPC spend, and earnings; provide support; prevent fraud and abuse; maintain security; and comply with applicable law."] },
  { title: "How information is shared", body: ["We share information when needed to provide the marketplace, including between an advertiser and a Community Owner involved in the same application or placement. We may share information with service providers that host, secure, analyze, or support the service, under appropriate contractual or confidentiality obligations.", "We may also disclose information if required by law, to protect rights and safety, investigate abuse, or support a business transfer. We do not sell personal information as a standalone product."] },
  { title: "Cookies and similar technologies", body: ["We may use cookies, local storage, and similar technologies to remember preferences, keep a workspace usable, understand basic usage, and protect tracking links. You can control cookies through your browser settings, although disabling them may affect parts of the service."] },
  { title: "Data security", body: ["We use reasonable administrative, technical, and organizational safeguards designed to protect information against unauthorized access, loss, misuse, or alteration. No internet service can guarantee absolute security, so please use a strong password and contact us promptly if you suspect unauthorized activity."] },
  { title: "Data retention", body: ["We retain information for as long as needed to provide the marketplace, maintain business and performance records, resolve disputes, prevent abuse, meet legal obligations, and enforce agreements. Retention periods vary based on the type of information and the reason it was collected. We delete or de-identify information when it is no longer reasonably needed, subject to lawful exceptions."] },
  { title: "User rights", body: ["Depending on where you live, you may have rights to request access to, correction of, deletion of, or a copy of your personal information, or to object to or restrict certain processing. You may also withdraw consent where processing is based on consent. To make a request, contact us using the details below. We may need to verify your identity before responding."] },
  { title: "Third-party services", body: ["The marketplace may link to or work with third-party services, including hosting, analytics, payment, communications, or advertiser destinations. Those services have their own privacy practices. This policy does not cover information collected directly by a third party after you leave our service."] },
  { title: "Children's privacy", body: ["The marketplace is intended for business and community operators and is not directed to children. We do not knowingly collect personal information from children in violation of applicable law. If you believe a child has provided information to us, contact us so we can review and remove it where appropriate."] },
  { title: "Policy updates", body: ["We may update this Privacy Policy as the marketplace, legal requirements, or our practices change. We will post the updated version here and revise the effective date. Your continued use of the marketplace after an update means you have had an opportunity to review the revised policy."] },
  { title: "Contact information", body: ["Questions, requests, or concerns about privacy can be sent to privacy@relay.market. Please include enough detail for us to understand your request and, when relevant, the account email associated with it."] },
];

export default function PrivacyPolicyPage() { return <div className="privacy-page"><header className="privacy-header"><Link href="/" className="public-brand"><span className="public-brand-mark"><i /><i /><i /></span>relay</Link><Link href="/" className="privacy-back"><ArrowLeft size={14} /> Back to main site</Link></header><main className="privacy-main"><div className="privacy-hero"><span className="privacy-kicker"><ShieldCheck size={14} /> Legal & privacy</span><h1>Privacy Policy</h1><p className="privacy-lede">This Privacy Policy explains how relay handles information when advertisers and Community Owners use our advertising marketplace.</p><p className="privacy-updated">Effective date: October 2, 2026</p></div><div className="privacy-layout"><aside className="privacy-contents"><strong>On this page</strong>{sections.map(section => <a href={`#${section.title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`} key={section.title}>{section.title}</a>)}</aside><article className="privacy-content"><div className="privacy-notice">This policy is written for the current frontend marketplace experience. It does not create authentication, payment, or consent functionality by itself.</div>{sections.map(section => <section id={section.title.toLowerCase().replace(/[^a-z0-9]+/g, "-")} className="privacy-section" key={section.title}><h2>{section.title}</h2>{section.body.map(paragraph => <p key={paragraph}>{paragraph}</p>)}</section>)}<div className="privacy-end"><p>Thank you for trusting relay with your marketplace activity.</p><Link href="/" className="public-text-link">Return to the main site <ArrowRight size={15} /></Link></div></article></div></main><footer className="privacy-footer"><span>© 2026 relay marketplace</span><Link href="/">Main site</Link><Link href="/login">Sign in</Link></footer></div>; }
