import { ArrowLeft, ArrowRight, FileText } from "lucide-react";
import { Link } from "wouter";

const sections = [
  { title: "Acceptance of terms", body: ["These Terms of Service govern your access to and use of relay, an advertising marketplace connecting advertisers with Community Owners. By creating an account, accessing a workspace, or using the marketplace, you agree to these Terms and any policies incorporated by reference.", "If you do not agree, do not use the marketplace. If you use relay on behalf of a business or organization, you represent that you have authority to bind that organization."] },
  { title: "Eligibility", body: ["You must be legally able to enter into a binding agreement to use the marketplace. The service is intended for businesses, advertisers, and Community Owners and is not directed to children. You may not use the service if applicable law prohibits you from doing so."] },
  { title: "Account responsibilities", body: ["You are responsible for providing accurate information, maintaining the confidentiality of your account credentials, and keeping your profile current. You must promptly notify relay if you believe your account has been accessed without authorization.", "You are responsible for activity conducted through your account and for ensuring that anyone acting for you follows these Terms. Do not share credentials or create accounts through deceptive means."] },
  { title: "Advertiser responsibilities", body: ["Advertisers are responsible for the accuracy, legality, and substantiation of campaigns, advertisements, landing pages, targeting criteria, budgets, CPC settings, and destination links they submit. Advertisers must have the rights and permissions needed to use their brand assets, claims, offers, and content.", "Advertisers must comply with applicable advertising, consumer-protection, privacy, intellectual-property, and platform rules. You must not ask Community Owners to make claims or take actions that violate those rules."] },
  { title: "Community Owner responsibilities", body: ["Community Owners are responsible for the accuracy of their community profile, platform information, audience description, location, and member estimates. You must have the right to publish approved advertisements in your community and must follow the relevant platform's rules.", "Community Owners may only publish approved advertisements as instructed. You must not artificially generate clicks, mislead members, conceal the commercial nature of an advertisement, or alter approved creative in a way that changes its meaning."] },
  { title: "Campaigns and advertisements", body: ["Campaigns are proposals created by Advertisers and may include budgets, CPC rates, audience requirements, dates, and approved advertising content. relay may review, reject, pause, limit, or remove campaigns or advertisements that do not meet marketplace requirements.", "An approved advertisement does not guarantee delivery, impressions, clicks, conversions, sales, or any particular business result. Advertisers remain responsible for the products, services, offers, and claims presented in their campaigns."] },
  { title: "Applications and placements", body: ["Community Owners may apply to campaigns, but an application does not create a placement. A placement is created only when the Advertiser accepts the application. The Advertiser may accept or reject applications and may manage placement availability according to campaign limits and requirements.", "Once accepted, a Community Owner must follow the campaign instructions and use the assigned placement and tracking link. Either party should promptly raise inaccurate information, broken destinations, or material changes that could affect a placement."] },
  { title: "Tracking links and qualified clicks", body: ["relay uses unique tracking links to attribute activity to accepted placements. A qualified click is a click that passes the marketplace's validation and attribution checks. Duplicate, automated, incentivized, fraudulent, or otherwise invalid activity may be excluded from performance, billing, or earnings calculations.", "Tracking links may redirect visitors to an advertiser's destination. Advertisers are responsible for the destination and its content. Community Owners must not hide, replace, manipulate, or repeatedly test tracking links in a way that creates misleading or invalid activity."] },
  { title: "Payments, fees, and earnings", body: ["Campaign budgets, CPC rates, platform fees, advertiser spend, and Community Owner earnings are displayed or calculated according to the marketplace configuration for the relevant campaign or placement. Earnings are based on qualified clicks and may be adjusted when activity is later determined to be invalid.", "Unless separately agreed in writing, relay does not promise a minimum budget, number of clicks, earnings amount, or payment timing. You are responsible for any taxes, reporting obligations, or fees that apply to your use of the marketplace. Payment functionality may depend on additional terms or third-party providers."] },
  { title: "Prohibited activities", body: ["You may not: violate law or third-party rights; submit deceptive or unlawful advertising; impersonate another person or business; create false profiles; interfere with marketplace operation; reverse engineer the service; introduce malware; scrape or harvest information without permission; manipulate clicks, applications, placements, budgets, or earnings; use bots or automated traffic; or attempt to bypass security or account limits.", "You may not use the marketplace for spam, discrimination, scams, adult or exploitative content, illegal goods or services, or any activity that could harm users, communities, advertisers, relay, or a third-party platform."] },
  { title: "Intellectual property", body: ["The marketplace, including its software, branding, design, text, features, and documentation, is owned by relay or its licensors and is protected by applicable intellectual-property laws. These Terms give you a limited, non-exclusive, non-transferable right to use the service for its intended purpose; they do not transfer ownership.", "You retain ownership of content you submit, subject to the rights you grant below and any rights needed to operate a campaign or placement."] },
  { title: "User-generated content", body: ["You grant relay a limited, worldwide, non-exclusive license to host, store, reproduce, display, adapt as technically necessary, and distribute your submitted content to provide, maintain, secure, and improve the marketplace and to facilitate the campaign or placement for which it was submitted.", "You represent that you have the rights needed to submit the content and grant this license. You are responsible for your content, and relay may remove content that violates these Terms, law, or the rights of others."] },
  { title: "Suspension and termination", body: ["You may stop using the marketplace at any time. relay may suspend, restrict, or terminate access, remove content, pause a campaign, or end a placement when reasonably necessary to protect users, investigate abuse, enforce these Terms, comply with law, or operate the service.", "After termination, rights and obligations that by their nature should continue will survive, including provisions concerning payments, intellectual property, disclaimers, limitation of liability, disputes, and user responsibilities."] },
  { title: "Disclaimers", body: ["The marketplace is provided on an 'as available' and 'as is' basis to the extent permitted by law. relay does not guarantee that the service will be uninterrupted, error-free, secure, or available at every time or location, or that any campaign, placement, click, audience, earning, conversion, or business outcome will meet your expectations.", "relay is a marketplace facilitator and is not a party to the underlying sale of an advertiser's products or services. You are responsible for evaluating the people, businesses, communities, offers, and destinations you choose to engage with."] },
  { title: "Limitation of liability", body: ["To the maximum extent permitted by law, relay and its affiliates, officers, employees, agents, and providers will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages, or for lost profits, revenue, data, goodwill, or business opportunities arising from or related to the marketplace.", "To the maximum extent permitted by law, relay's total liability for claims arising from the marketplace will not exceed the greater of the amount you paid relay for the service in the twelve months before the event giving rise to the claim or one hundred U.S. dollars. Some jurisdictions do not allow certain limitations, so parts of this section may not apply to you."] },
  { title: "Dispute and general provisions", body: ["Before bringing a formal claim, you agree to contact relay and give us a reasonable opportunity to address the issue. These Terms, together with referenced policies, form the agreement between you and relay about the marketplace and replace prior understandings about the same subject.", "If a provision is found unenforceable, the remaining provisions will remain in effect. You may not assign these Terms without our consent; relay may assign them in connection with a merger, acquisition, reorganization, or sale of assets. No waiver is a continuing waiver. Applicable governing law and venue will be determined by the agreement and mandatory law applicable to your location."] },
  { title: "Changes to the terms", body: ["We may update these Terms when the marketplace, our practices, or legal requirements change. We will post the revised Terms and update the effective date. Where required, we will provide additional notice. By continuing to use the marketplace after the revised Terms become effective, you agree to the changes."] },
  { title: "Contact information", body: ["Questions about these Terms can be sent to legal@relay.market. Please include your name, account email, and a clear description of your question so we can respond efficiently."] },
];

const slug = (title: string) => title.toLowerCase().replace(/[^a-z0-9]+/g, "-");

export default function TermsPage() { return <div className="privacy-page"><header className="privacy-header"><Link href="/" className="public-brand"><span className="public-brand-mark"><i /><i /><i /></span>relay</Link><Link href="/" className="privacy-back"><ArrowLeft size={14} /> Back to main site</Link></header><main className="privacy-main"><div className="privacy-hero"><span className="privacy-kicker"><FileText size={14} /> Legal & terms</span><h1>Terms of Service</h1><p className="privacy-lede">These Terms explain the rules for using relay, the advertising marketplace connecting Advertisers with Community Owners.</p><p className="privacy-updated">Effective date: October 2, 2026</p></div><div className="privacy-layout"><aside className="privacy-contents"><strong>On this page</strong>{sections.map(section => <a href={`#${slug(section.title)}`} key={section.title}>{section.title}</a>)}</aside><article className="privacy-content"><div className="privacy-notice">These Terms describe the current frontend marketplace experience. They do not create authentication, payment processing, or backend functionality by themselves.</div>{sections.map(section => <section id={slug(section.title)} className="privacy-section" key={section.title}><h2>{section.title}</h2>{section.body.map(paragraph => <p key={paragraph}>{paragraph}</p>)}</section>)}<div className="privacy-end"><p>Thank you for using relay responsibly and helping build a better advertising marketplace.</p><Link href="/" className="public-text-link">Return to the main site <ArrowRight size={15} /></Link></div></article></div></main><footer className="privacy-footer"><span>© 2026 relay marketplace</span><Link href="/">Main site</Link><Link href="/privacy">Privacy</Link><Link href="/login">Sign in</Link></footer></div>; }
