import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";

export type TrackingRegistryRecord = { trackingId: string; campaignId: string; placementId: string; communityId: string; communityOwnerId: string; destinationUrl: string; placementStatus: string; campaignStatus: string; cpc: string; budget: string; createdAt: string };
export type ServerClickEvent = { clickId: string; trackingId: string; campaignId: string; placementId: string; communityId: string; communityOwnerId: string; timestamp: string; qualification: "Qualified" | "Rejected"; destinationUrl: string; rejectionReason?: string; visitorKey: string };

type TrackingDb = { registry: TrackingRegistryRecord[]; clicks: ServerClickEvent[] };
const dataDir = path.resolve(process.cwd(), ".data");
const dataFile = path.join(dataDir, "tracking.json");

function readDb(): TrackingDb { try { const raw = fs.readFileSync(dataFile, "utf8"); const parsed = JSON.parse(raw) as Partial<TrackingDb>; return { registry: parsed.registry ?? [], clicks: parsed.clicks ?? [] }; } catch { return { registry: [], clicks: [] }; } }
function writeDb(db: TrackingDb) { fs.mkdirSync(dataDir, { recursive: true }); const temp = `${dataFile}.tmp`; fs.writeFileSync(temp, JSON.stringify(db, null, 2)); fs.renameSync(temp, dataFile); }
export function upsertTrackingRecord(record: TrackingRegistryRecord) { const db = readDb(); db.registry = [...db.registry.filter((item) => item.trackingId !== record.trackingId), record]; writeDb(db); return record; }
export function getTrackingRecord(trackingId: string) { return readDb().registry.find((record) => record.trackingId === trackingId); }
export function getServerClickEvents() { return readDb().clicks; }
export function getPlacementServerStats(placementId: string) { const clicks = readDb().clicks.filter((event) => event.placementId === placementId); return { total: clicks.length, qualified: clicks.filter((event) => event.qualification === "Qualified").length, rejected: clicks.filter((event) => event.qualification === "Rejected").length }; }
export function getCampaignServerStats(campaignId: string) { const clicks = readDb().clicks.filter((event) => event.campaignId === campaignId); return { total: clicks.length, qualified: clicks.filter((event) => event.qualification === "Qualified").length, rejected: clicks.filter((event) => event.qualification === "Rejected").length }; }
export function createVisitorKey(ip: string, userAgent: string, trackingId: string) { return crypto.createHash("sha256").update(`${ip}|${userAgent}|${trackingId}`).digest("hex"); }
export function recordServerClick(record: TrackingRegistryRecord, request: { ip: string; userAgent: string; referrer: string }) { const db = readDb(); const visitorKey = createVisitorKey(request.ip, request.userAgent, record.trackingId); const now = Date.now(); let qualification: ServerClickEvent["qualification"] = "Qualified"; let rejectionReason: string | undefined; const recentDuplicate = db.clicks.some((event) => event.trackingId === record.trackingId && event.visitorKey === visitorKey && event.qualification === "Qualified" && now - new Date(event.timestamp).getTime() < 60_000); if (record.placementStatus !== "Active") { qualification = "Rejected"; rejectionReason = "Placement is not active"; } else if (record.campaignStatus !== "Active") { qualification = "Rejected"; rejectionReason = "Campaign is not active"; } else if (!/^https?:\/\//i.test(record.destinationUrl)) { qualification = "Rejected"; rejectionReason = "Missing or invalid destination"; } else if (recentDuplicate) { qualification = "Rejected"; rejectionReason = "Repeated click from the same visitor within the prototype window"; } else { const qualified = db.clicks.filter((event) => event.campaignId === record.campaignId && event.qualification === "Qualified").length; const cpc = Number(record.cpc.replace(/[^0-9.]/g, "")) || 0; const budget = Number(record.budget.replace(/[^0-9.]/g, "")) || 0; if (cpc <= 0 || qualified >= Math.floor(budget / cpc)) { qualification = "Rejected"; rejectionReason = "Campaign budget exhausted"; } }
  const event: ServerClickEvent = { clickId: `${record.trackingId}-${Date.now()}-${crypto.randomBytes(4).toString("hex")}`, trackingId: record.trackingId, campaignId: record.campaignId, placementId: record.placementId, communityId: record.communityId, communityOwnerId: record.communityOwnerId, timestamp: new Date().toISOString(), qualification, destinationUrl: record.destinationUrl, rejectionReason, visitorKey }; db.clicks.push(event); writeDb(db); return event;
}
