import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowUpRight, BarChart3, CheckCircle2, DollarSign, MousePointer2, Receipt, WalletCards } from "lucide-react";
import { Link } from "wouter";
import WorkspaceShell from "@/components/WorkspaceShell";
import { formatMoney, getCampaignFinancials, getCpcBreakdown, getClickEvents, readCampaigns, type CampaignRecord, type MarketplaceClickEvent } from "@/data/marketplaceData";

type BillingRow = { campaign: CampaignRecord; clicks: MarketplaceClickEvent[]; financials: ReturnType<typeof getCampaignFinancials> };
function dateLabel(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? value : date.toLocaleString("en-KE", { dateStyle: "medium", timeStyle: "short" }); }
function readBillingSnapshot() { const campaigns = readCampaigns(); const clicks = getClickEvents(); return campaigns.map((campaign) => { const qualified = clicks.filter((click) => click.campaignId === campaign.id && click.qualification === "Qualified"); return { campaign, clicks: qualified, financials: getCampaignFinancials(campaign.cpc, campaign.budget, qualified.length) }; }); }

export default function CampaignOwnerBilling() {
  const [rows, setRows] = useState<BillingRow[]>(readBillingSnapshot);
  useEffect(() => { const refresh = () => setRows(readBillingSnapshot()); const events = ["storage", "ownerboard:click-events-updated", "ownerboard:campaigns-updated"]; events.forEach((event) => window.addEventListener(event, refresh)); refresh(); return () => events.forEach((event) => window.removeEventListener(event, refresh)); }, []);
  const totals = useMemo(() => rows.reduce((sum, row) => ({ spend: sum.spend + row.financials.advertiserSpend, fees: sum.fees + row.financials.platformRevenue, payouts: sum.payouts + row.financials.communityOwnerEarnings, clicks: sum.clicks + row.financials.qualifiedClicks, remaining: sum.remaining + row.financials.remainingBudget, budget: sum.budget + Number(row.campaign.budget.replace(/[^0-9.]/g, "")) }), { spend: 0, fees: 0, payouts: 0, clicks: 0, remaining: 0, budget: 0 }), [rows]);
  const activeSpend = rows.filter((row) => row.campaign.status === "Active").reduce((sum, row) => sum + row.financials.advertiserSpend, 0);
  const spendingCampaigns = rows.filter((row) => row.financials.advertiserSpend > 0).length;
  const activity = rows.flatMap((row) => row.clicks.map((click) => ({ click, campaign: row.campaign, breakdown: getCpcBreakdown(row.campaign.cpc) }))).sort((a, b) => new Date(b.click.timestamp).getTime() - new Date(a.click.timestamp).getTime()).slice(0, 8);
  return <WorkspaceShell active="Billing" workspaceLabel="Campaign Owner" workspaceMode="campaign-owner">
    <div className="dashboard-body campaign-owner-overview"><Link className="hero-link route-back-link" href="/campaign-owner"><ArrowLeft size={15} /> Back to Campaign Owner overview</Link>
      <section className="campaign-owner-heading"><div><span className="section-kicker"><span className="section-kicker-line" /> Campaign Owner billing</span><h1>Billing overview</h1><p>Track qualified-click spend, platform fees, Community Owner payouts, and remaining campaign budget from your live marketplace data.</p></div><Link className="primary-owner-button" href="/campaign-owner/campaigns"><BarChart3 size={16} /> View campaigns</Link></section>
      <div className="campaign-owner-metric-grid"><BillingMetric label="Total campaign spend" value={formatMoney(totals.spend)} detail={`${totals.clicks.toLocaleString()} qualified clicks`} icon={DollarSign} tone="coral" /><BillingMetric label="Platform fees" value={formatMoney(totals.fees)} detail="25% of qualified-click charges" icon={Receipt} tone="lilac" /><BillingMetric label="Community Owner payouts" value={formatMoney(totals.payouts)} detail="Existing CPC payout calculation" icon={WalletCards} tone="moss" /><BillingMetric label="Remaining campaign budget" value={formatMoney(totals.remaining)} detail={`${formatMoney(totals.budget)} total budget`} icon={CheckCircle2} tone="lilac" /><BillingMetric label="Active campaign spend" value={formatMoney(activeSpend)} detail="Active campaigns only" icon={BarChart3} tone="coral" /><BillingMetric label="Campaigns with spending" value={spendingCampaigns} detail={`${rows.length} campaigns in billing data`} icon={MousePointer2} tone="moss" /></div>
      <section className="campaign-owner-two-column"><section className="campaign-owner-section"><div className="section-heading"><div><div className="section-kicker"><span className="section-kicker-line section-kicker-line-lilac" /> Campaign ledger</div><h2>Spend by campaign</h2></div><span className="section-count">{rows.length} campaigns</span></div><div className="campaign-owner-campaign-grid">{rows.map((row) => <Link className="campaign-owner-campaign-card" href={`/campaign-owner/campaigns/${row.campaign.id}`} key={row.campaign.id}><div className="campaign-owner-campaign-top"><span className={`campaign-owner-status campaign-owner-status-${row.campaign.status === "Active" ? "moss" : row.campaign.status === "Completed" || row.campaign.status === "Budget Exhausted" ? "coral" : "lilac"}`}><span /> {row.campaign.status}</span><ArrowUpRight size={17} /></div><h3>{row.campaign.name}</h3><div className="campaign-owner-campaign-meta"><span><strong>{formatMoney(row.financials.advertiserSpend)}</strong><small>campaign spend</small></span><span><strong>{row.financials.qualifiedClicks.toLocaleString()}</strong><small>qualified clicks</small></span><span><strong>{formatMoney(row.financials.remainingBudget)}</strong><small>budget left</small></span></div><div className="campaign-owner-campaign-footer"><span>{formatMoney(row.financials.platformRevenue)} platform fee</span><ArrowUpRight size={14} /></div></Link>)}</div>{rows.length === 0 && <div className="campaign-applications-empty"><CheckCircle2 size={21} /><strong>No campaigns in billing yet</strong><p>Create a campaign to begin tracking billing activity.</p></div>}</section><div className="campaign-owner-budget-card"><div className="section-heading"><div><div className="section-kicker"><span className="section-kicker-line section-kicker-line-lilac" /> Budget health</div><h2>Portfolio budget</h2></div><DollarSign size={18} /></div><strong className="campaign-owner-budget-number">{formatMoney(totals.spend)}</strong><div className="campaign-owner-budget-bar"><span style={{ width: `${totals.budget ? Math.min((totals.spend / totals.budget) * 100, 100) : 0}%` }} /></div><div className="campaign-owner-budget-labels"><span>{totals.budget ? Math.round((totals.spend / totals.budget) * 100) : 0}% used</span><span>{formatMoney(totals.remaining)} left</span></div><p className="campaign-owner-billing-note">Historical spend remains included for Completed, Paused, and Budget Exhausted campaigns.</p><Link className="section-link" href="/campaign-owner/performance">Open performance <ArrowUpRight size={14} /></Link></div></section>
      <section className="campaign-owner-section"><div className="section-heading"><div><div className="section-kicker"><span className="section-kicker-line" /> Recent billing activity</div><h2>Qualified-click transactions</h2></div><span className="section-count">Existing financial records</span></div><div className="campaign-owner-application-list">{activity.map(({ click, campaign, breakdown }) => <div className="campaign-owner-application-row" key={click.clickId}><span className="campaign-owner-application-avatar campaign-owner-application-avatar-moss"><MousePointer2 size={14} /></span><span><strong>{campaign.name}</strong><small>{dateLabel(click.timestamp)} · {click.trackingId}</small></span><b>{formatMoney(breakdown.advertiserCpc)} spend · {formatMoney(breakdown.platformFee)} fee</b><CheckCircle2 size={15} /></div>)}{activity.length === 0 && <div className="campaign-applications-empty"><CheckCircle2 size={21} /><strong>No qualified-click billing activity yet</strong><p>Billing activity will appear here when existing tracking records contain qualified clicks.</p></div>}</div></section>
    </div>
  </WorkspaceShell>;
}
function BillingMetric({ label, value, detail, icon: Icon, tone }: { label: string; value: string | number; detail: string; icon: typeof DollarSign; tone: "coral" | "lilac" | "moss" }) { return <article className={`campaign-owner-metric campaign-owner-metric-${tone}`}><span className="campaign-owner-metric-icon"><Icon size={17} /></span><span><small>{label}</small><strong>{value}</strong><em>{detail}</em></span></article>; }
