import { CampaignOwnerApplication, readApplications } from "./applicationData";
import { CampaignRecord, readCampaigns } from "./campaignData";
import { formatMoney, getCampaignClickStats, getCampaignFinancials, getCpcBreakdown, getPlacementClickStats, getTrackingPath, moneyToNumber } from "@/data/marketplaceData";

export type CampaignOwnerPlacement = CampaignOwnerApplication & { campaignStatus: CampaignRecord["status"]; campaignBudget: string; campaignSpend: string; remainingBudget: string; advertiserCpc: string; qualifiedClicks: number; totalCommunityOwnerEarnings: string; platformRevenue: string; clicks: number; trackingLink: string; advertisement: string };
function fallbackCampaign(application: CampaignOwnerApplication): CampaignRecord { return { id: application.campaignId, name: application.campaign, advertiser: application.advertiser, description: "Campaign placement", advertisement: `Discover ${application.campaign} with ${application.advertiser}. Tap through to learn more and get started today.`, destinationUrl: "#", platforms: [application.platform], category: application.category, location: application.location, minAudience: "0", maxAudience: "0", duration: application.duration, maxCommunities: "1", cpc: application.cpc, budget: application.cpc, startDate: application.startDate, endDate: application.endDate, status: "Published", applications: 0, placements: 0, clicks: 0 }; }
export function readPlacements() { const campaigns = readCampaigns(); const applications = readApplications(); return applications.filter((application) => application.status === "Accepted").map((application) => { const campaign = campaigns.find((item) => item.id === application.campaignId) ?? fallbackCampaign(application); const clickStats = getPlacementClickStats(application.id); const financials = getCampaignFinancials(campaign.cpc, campaign.budget, clickStats.qualified); return { ...application, campaignStatus: campaign.status, campaignBudget: campaign.budget, campaignSpend: formatMoney(financials.advertiserSpend, 2), remainingBudget: formatMoney(financials.remainingBudget, 2), advertiserCpc: formatMoney(financials.advertiserCpc, 2), qualifiedClicks: financials.qualifiedClicks, totalCommunityOwnerEarnings: formatMoney(financials.communityOwnerEarnings, 2), platformRevenue: formatMoney(financials.platformRevenue, 2), clicks: financials.qualifiedClicks, trackingLink: getTrackingPath(application.trackingId ?? `missing-${application.id}`), advertisement: campaign.advertisement } satisfies CampaignOwnerPlacement; }); }
export function getPerformanceSummary(placements: CampaignOwnerPlacement[], campaigns: CampaignRecord[]) { const acceptedCampaignIds = new Set(placements.map((placement) => placement.campaignId)); const relevantCampaigns = campaigns.filter((campaign) => acceptedCampaignIds.has(campaign.id)); const financials = relevantCampaigns.map((campaign) => getCampaignFinancials(campaign.cpc, campaign.budget, getCampaignClickStats(campaign.id).qualified)); const spend = financials.reduce((total, item) => total + item.advertiserSpend, 0); const budget = relevantCampaigns.reduce((total, campaign) => total + moneyToNumber(campaign.budget), 0); const clicks = financials.reduce((total, item) => total + item.qualifiedClicks, 0); return { totalClicks: clicks, activePlacements: placements.filter((placement) => placement.campaignStatus !== "Completed").length, completedPlacements: placements.filter((placement) => placement.campaignStatus === "Completed").length, campaignSpend: formatMoney(Math.min(spend, budget), 2), remainingBudget: formatMoney(Math.max(budget - spend, 0), 2) }; }
export { formatMoney, moneyToNumber, getCpcBreakdown, getCampaignFinancials };
