(() => {
  const AUTH_KEY = "relay-admin-auth";
  const demoEmail = "admin@relay.local";
  const demoPassword = "admin123";
  const path = location.pathname.split("/").filter(Boolean).pop() || "admin";
  const isLogin = document.body.classList.contains("admin-login-page");
  if (isLogin) {
    document.getElementById("admin-login-form")?.addEventListener("submit", (event) => {
      event.preventDefault();
      const email = document.getElementById("admin-email").value.trim();
      const password = document.getElementById("admin-password").value;
      const error = document.getElementById("login-error");
      if (email !== demoEmail || password !== demoPassword) { error.textContent = "Use the demo admin credentials shown in the project README."; return; }
      sessionStorage.setItem(AUTH_KEY, JSON.stringify({ email, signedInAt: new Date().toISOString() }));
      location.href = "./dashboard.html";
    });
    return;
  }
  if (!sessionStorage.getItem(AUTH_KEY)) { location.href = "./index.html"; return; }
  const navItems = [
    ["dashboard.html", "⌂", "Overview"], ["campaigns.html", "◈", "Campaigns"], ["users.html", "♙", "Users"], ["applications.html", "◇", "Applications"], ["placements.html", "⌁", "Placements"], ["activity.html", "↗", "Activity"], ["settings.html", "⚙", "Settings"]
  ];
  const titles = { dashboard: ["Overview", "Marketplace health at a glance"], campaigns: ["Campaigns", "Review advertiser campaigns and lifecycle status"], users: ["Users", "Manage Campaign Owners and Community Owners"], applications: ["Applications", "Review the marketplace application queue"], placements: ["Placements", "Monitor accepted communities and delivery"], activity: ["Activity", "A chronological record of platform movement"], settings: ["Settings", "Configure the independent admin workspace"] };
  const current = path.replace(".html", "") || "dashboard";
  const title = titles[current] || titles.dashboard;
  const shell = document.getElementById("admin-app");
  shell.innerHTML = `<aside class="admin-sidebar"><div class="sidebar-brand"><span class="wordmark-mark">r</span><span>relay</span><small>ADMIN</small></div><span class="side-label">Operations</span><nav class="side-nav">${navItems.map(([href, icon, label]) => `<a href="./${href}" class="${current === href.replace('.html','') ? 'active' : ''}"><span class="nav-icon">${icon}</span>${label}</a>`).join('')}</nav><div class="sidebar-spacer"></div><div class="admin-user"><span class="admin-avatar">AD</span><span><strong>Admin Director</strong><small>admin@relay.local</small></span><button class="signout" id="signout" title="Sign out">↪</button></div></aside><main class="admin-main"><header class="admin-topbar"><button class="mobile-menu">☰</button><span class="crumb">Relay / Admin / <strong>${title[0]}</strong></span><div class="top-actions"><button title="Notifications">♢</button><span class="date-note">Friday, 03 October 2026</span></div></header><div class="admin-main-content"><div class="page-heading"><div><span class="eyebrow">Admin console</span><h1>${title[0]}</h1><p>${title[1]}</p></div><span class="date-note">Independent access · Frontend prototype</span></div><div id="page-content"></div></div></main>`;
  document.getElementById("signout")?.addEventListener("click", () => { sessionStorage.removeItem(AUTH_KEY); location.href = "./index.html"; });
  renderPage(current);
  function renderPage(page) {
    const root = document.getElementById("page-content");
    if (page === "dashboard") root.innerHTML = `<section class="stats-grid"><div class="stat-card"><small>Total campaigns</small><strong>24</strong><span class="stat-trend">↑ 8.4% this month</span></div><div class="stat-card"><small>Active placements</small><strong>38</strong><span class="stat-trend">↑ 12.1% this month</span></div><div class="stat-card"><small>Qualified clicks</small><strong>42,860</strong><span class="stat-trend">↑ 16.8% this month</span></div><div class="stat-card"><small>Platform revenue</small><strong>KSh 214k</strong><span class="stat-trend">↑ 9.2% this month</span></div></section><div class="content-grid"><section class="panel"><div class="panel-heading"><h2>Campaign overview</h2><a href="./campaigns.html">View all →</a></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>Campaign</th><th>Owner</th><th>Status</th><th>Clicks</th></tr></thead><tbody>${campaignRows()}</tbody></table></div></section><section class="panel"><div class="panel-heading"><h2>Latest activity</h2><a href="./activity.html">History →</a></div>${activityRows()}</section></div>`;
    if (page === "campaigns") root.innerHTML = `<div class="filter-bar"><input placeholder="Search campaigns" /><select><option>All statuses</option><option>Active</option><option>Published</option><option>Paused</option><option>Completed</option></select></div><section class="panel"><div class="panel-heading"><h2>Campaign registry</h2><span class="pill blue">24 campaigns</span></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>Campaign</th><th>Campaign Owner</th><th>Status</th><th>Budget</th><th>Clicks</th><th></th></tr></thead><tbody>${campaignRows(true)}</tbody></table></div></section>`;
    if (page === "users") root.innerHTML = `<section class="panel"><div class="panel-heading"><h2>Marketplace users</h2><span class="pill blue">186 users</span></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>User</th><th>Role</th><th>Joined</th><th>Status</th><th></th></tr></thead><tbody>${userRows()}</tbody></table></div></section>`;
    if (page === "applications") root.innerHTML = `<section class="panel"><div class="panel-heading"><h2>Application queue</h2><span class="pill amber">8 pending review</span></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>Community</th><th>Campaign</th><th>Platform</th><th>Status</th><th></th></tr></thead><tbody>${applicationRows()}</tbody></table></div></section>`;
    if (page === "placements") root.innerHTML = `<section class="panel"><div class="panel-heading"><h2>Placement delivery</h2><span class="pill green">38 active</span></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>Community</th><th>Campaign</th><th>Clicks</th><th>Status</th><th>Earnings</th></tr></thead><tbody>${placementRows()}</tbody></table></div></section>`;
    if (page === "activity") root.innerHTML = `<section class="panel"><div class="panel-heading"><h2>Platform activity history</h2><span class="pill blue">Live registry</span></div><div class="activity-list">${activityRows(true)}</div></section>`;
    if (page === "settings") root.innerHTML = `<div class="content-grid"><section class="panel"><div class="panel-heading"><h2>Admin profile</h2></div><div class="admin-form"><label>Display name<input value="Admin Director" /></label><label>Admin email<input value="admin@relay.local" /></label><button class="primary-button">Save profile <span>→</span></button></div></section><section class="panel"><div class="panel-heading"><h2>Access boundary</h2></div><p class="muted">This portal is intentionally isolated from the main marketplace routes and frontend authentication flow.</p><span class="pill green">Separate admin root enabled</span></section></div>`;
  }
  function campaignRows(full=false){ return [['Urban Sneakers Launch','Urban Sneakers','Active','KSh 40,000','8,420'],['Safaricom Home Fibre','Safaricom','Published','KSh 108,000','18,420'],['M-PESA Business Growth','Safaricom M-PESA','Paused','KSh 122,500','12,860'],['Jiji Weekend Finds','Jiji Kenya','Completed','KSh 84,000','11,400']].map(([name,owner,status,budget,clicks])=>`<tr><td><span class="entity"><span class="entity-mark">${name[0]}</span><span><strong>${name}</strong><small>${owner}</small></span></span></td><td>${owner}</td><td><span class="pill ${status==='Active'?'green':status==='Paused'?'amber':status==='Completed'?'blue':'blue'}">${status}</span></td>${full?`<td>${budget}</td>`:''}<td>${clicks}</td>${full?'<td><button class="danger-link">Review</button></td>':''}</tr>`).join(''); }
  function userRows(){ return [['Ava Sinclair','Community Owner','Jun 17, 2025','Active'],['Daniel Mwangi','Campaign Owner','Jun 16, 2025','Active'],['Njeri Kamau','Community Owner','Jun 12, 2025','Pending'],['Brian Otieno','Campaign Owner','Jun 08, 2025','Active']].map(([name,role,date,status])=>`<tr><td><span class="entity"><span class="entity-mark">${name.split(' ').map(x=>x[0]).join('')}</span><span><strong>${name}</strong><small>${name.toLowerCase().replace(' ',' .')}@relay.local</small></span></span></td><td>${role}</td><td>${date}</td><td><span class="pill ${status==='Active'?'green':'amber'}">${status}</span></td><td><button class="danger-link">View</button></td></tr>`).join(''); }
  function applicationRows(){ return [['Nairobi Sneaker Deals','Urban Sneakers Launch','WhatsApp','Pending'],['Kibera Entrepreneurs','M-PESA Business Growth','Telegram','Accepted'],['Nairobi Tech Circle','Safaricom Home Fibre','WhatsApp','Pending'],['After Hours Kenya','Jiji Weekend Finds','Discord','Rejected']].map(([community,campaign,platform,status])=>`<tr><td><span class="entity"><span class="entity-mark">${community[0]}</span><strong>${community}</strong></span></td><td>${campaign}</td><td>${platform}</td><td><span class="pill ${status==='Accepted'?'green':status==='Rejected'?'red':'amber'}">${status}</span></td><td><button class="danger-link">Review</button></td></tr>`).join(''); }
  function placementRows(){ return [['Nairobi Sneaker Deals','Urban Sneakers Launch','2,940','Active','KSh 4,410'],['Kibera Entrepreneurs','M-PESA Business Growth','1,860','Active','KSh 2,790'],['Nairobi Tech Circle','Safaricom Home Fibre','8,420','Ready to Post','KSh 0'],['After Hours Kenya','Jiji Weekend Finds','11,400','Completed','KSh 17,100']].map(([community,campaign,clicks,status,earnings])=>`<tr><td><strong>${community}</strong></td><td>${campaign}</td><td>${clicks}</td><td><span class="pill ${status==='Active'?'green':status==='Completed'?'blue':'amber'}">${status}</span></td><td>${earnings}</td></tr>`).join(''); }
  function activityRows(){ return [['Campaign Activated','Urban Sneakers Launch · Nairobi Sneaker Deals','12 minutes ago'],['Application accepted','M-PESA Business Growth · Kibera Entrepreneurs','1 hour ago'],['Campaign Published','Safaricom Home Fibre','3 hours ago'],['Campaign Budget Exhausted','Jiji Weekend Finds','Yesterday']].map(([title,detail,time])=>`<div class="activity-item"><span class="activity-dot">↗</span><span><strong>${title}</strong><small>${detail} · ${time}</small></span></div>`).join(''); }
})();
