import { useState } from "react";
import { ArrowRight, LockKeyhole, Mail } from "lucide-react";
import { Link, useLocation } from "wouter";
import { ADMIN_AUTH_KEY } from "./AdminShell";
import "./admin.css";
import { loginRelayAccount, relayBackendEnabled } from "@/lib/relayApi";

export default function AdminLogin() {
  const [, navigate] = useLocation();
  const [email, setEmail] = useState("admin@relay.local");
  const [password, setPassword] = useState("admin123");
  const [error, setError] = useState("");
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!email.trim() || !password) { setError(!email.trim() ? "Enter your Admin email address." : "Enter your Admin password."); return; } if (relayBackendEnabled()) { try { const user = await loginRelayAccount(email, password); if (user.role !== "Admin") { setError("This account does not have Admin access."); return; } setError(""); sessionStorage.setItem(ADMIN_AUTH_KEY, JSON.stringify({ email, signedInAt: new Date().toISOString(), backend: true })); navigate("/admin/dashboard"); return; } catch { setError("Invalid Relay Admin credentials or unavailable backend."); return; } } if (email !== "admin@relay.local" || password !== "admin123") { setError("Invalid Admin credentials. Use the demo credentials supplied with this portal."); return; } setError(""); sessionStorage.setItem(ADMIN_AUTH_KEY, JSON.stringify({ email, signedInAt: new Date().toISOString() })); navigate("/admin/dashboard"); };
  return <main className="admin-react-login"><section className="admin-react-login-brand"><Link href="/" className="admin-react-login-back">← Back to marketplace</Link><div className="admin-react-brand"><span className="public-brand-mark admin-react-brand-mark"><i /><i /><i /></span><span>relay</span><small>ADMIN CONSOLE</small></div><div className="admin-react-login-copy"><span className="admin-react-eyebrow">Private operations workspace</span><h1>Keep the marketplace moving.</h1><p>Review campaigns, communities, applications, placements, and platform activity from one protected console.</p></div><footer>Independent admin portal · Frontend prototype</footer></section><section className="admin-react-login-form"><div><span className="admin-react-eyebrow">Admin access</span><h2>Welcome back</h2><p>Sign in to continue to the Relay operations console.</p><form onSubmit={submit} noValidate><label>Email address<div className={`admin-react-login-input-wrap${error && !email.trim() ? " has-error" : ""}`}><Mail size={16} /><input type="email" value={email} onChange={(event) => { setEmail(event.target.value); setError(""); }} placeholder="admin@relay.local" aria-invalid={Boolean(error && !email.trim())} /></div></label><label>Password<div className={`admin-react-login-input-wrap${error && !password ? " has-error" : ""}`}><LockKeyhole size={16} /><input type="password" value={password} onChange={(event) => { setPassword(event.target.value); setError(""); }} placeholder="Enter your password" aria-invalid={Boolean(error && !password)} /></div></label><div className="admin-react-login-options"><span>Protected workspace</span><Link href="/admin/forgot-password">Forgot password?</Link></div>{error && <small className="admin-react-error" role="alert">{error}</small>}<button className="admin-react-primary" type="submit">Sign in to Admin <ArrowRight size={16} /></button></form><div className="admin-react-login-note">⌁ This is a separate Admin-only frontend prototype.</div></div></section></main>;
}
