import { useEffect, useState, type ReactNode } from "react";
import AdminShell from "./AdminShell";
import AdminState from "./AdminState";
import { formatMoney, getCampaignClickStats, getCampaignFinancials, getClickEvents, readCampaignActivities, readApplications, readCampaigns, readCommunities, syncServerClickEvents } from "@/data/marketplaceData";
import type { CampaignActivity, CampaignRecord, MarketplaceApplication, MarketplaceClickEvent, MarketplaceCommunity } from "@/data/marketplaceData";

export type AdminSnapshot = { campaigns: CampaignRecord[]; applications: MarketplaceApplication[]; clicks: MarketplaceClickEvent[]; activities: CampaignActivity[]; communities: MarketplaceCommunity[] };
export function useAdminMarketplace(): AdminSnapshot {
  const read = () => ({ campaigns: readCampaigns(), applications: readApplications(), clicks: getClickEvents(), activities: readCampaignActivities(), communities: readCommunities() });
  const [snapshot, setSnapshot] = useState<AdminSnapshot>(read);
  useEffect(() => { const refresh = () => setSnapshot(read()); refresh(); void syncServerClickEvents().then(refresh); const events = ["storage", "ownerboard:applications-updated", "ownerboard:click-events-updated", "ownerboard:activity-updated", "ownerboard:campaigns-updated", "ownerboard:communities-updated"]; events.forEach((event) => window.addEventListener(event, refresh)); return () => events.forEach((event) => window.removeEventListener(event, refresh)); }, []);
  return snapshot;
}

export function statusPill(status: string) { const tone = status === "Active" || status === "Accepted" || status === "Verified" ? "green" : status === "Paused" || status === "Pending" || status === "Ready to Post" || status === "Pending verification" ? "amber" : status === "Rejected" ? "red" : "blue"; return <span className={`admin-react-pill ${tone}`}>{status}</span>; }
export function campaignFinancials(campaign: CampaignRecord, clicks: MarketplaceClickEvent[]) { return getCampaignFinancials(campaign.cpc, campaign.budget, clicks.filter((event) => event.campaignId === campaign.id && event.qualification === "Qualified").length); }
function TablePanel({ title, action, headers, rows }: { title: string; action?: ReactNode; headers: string[]; rows: ReactNode[][] }) { return <section className="admin-react-panel"><div className="admin-react-panel-heading"><h2>{title}</h2>{action}</div><div className="admin-react-table-wrap"><table className="admin-react-table"><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{rows.length ? rows.map((row, index) => <tr key={index}>{row.map((cell, cellIndex) => <td key={cellIndex}>{cell}</td>)}</tr>) : <tr><td colSpan={headers.length}><AdminState title="No records yet" description="Records will appear here as marketplace activity is created." actionLabel="Return to overview" href="/admin/dashboard" compact /></td></tr>}</tbody></table></div></section>; }
const action = (label: string) => <button className="admin-react-table-action" type="button">{label}</button>;

export function AdminCampaignsPage() { const { campaigns, applications, clicks } = useAdminMarketplace(); return <AdminShell title="Campaigns" subtitle="Review advertiser campaigns and lifecycle status"><TablePanel title={`${campaigns.length} campaigns in marketplace`} action={<span className="admin-react-pill blue">Live state</span>} headers={["Campaign", "Owner", "Status", "Applications", "Clicks", "Spend"]} rows={campaigns.map((campaign) => { const financials = campaignFinancials(campaign, clicks); return [<strong>{campaign.name}</strong>, campaign.advertiser, statusPill(campaign.status), applications.filter((item) => item.campaignId === campaign.id).length, financials.qualifiedClicks.toLocaleString(), formatMoney(financials.advertiserSpend)]; })} /></AdminShell>; }
export function AdminUsersPage() { const { campaigns, communities } = useAdminMarketplace(); const advertisers = Array.from(new Set(campaigns.map((campaign) => campaign.advertiser))); const owners = Array.from(new Set(communities.map((community) => community.ownerId))); const rows = [...advertisers.map((name) => [<strong>{name}</strong>, "Campaign Owner", `${campaigns.filter((campaign) => campaign.advertiser === name).length} campaigns`, statusPill("Active")]), ...owners.map((owner) => [<strong>{owner.replaceAll("-", " ")}</strong>, "Community Owner", `${communities.filter((community) => community.ownerId === owner).length} communities`, statusPill("Active")])]; return <AdminShell title="Users" subtitle="Manage participants derived from current marketplace records"><TablePanel title={`${rows.length} marketplace profiles`} headers={["Profile", "Role", "Portfolio", "Status"]} rows={rows} /></AdminShell>; }
export function AdminApplicationsPage() { const { applications } = useAdminMarketplace(); return <AdminShell title="Applications" subtitle="Review the marketplace application queue"><TablePanel title={`${applications.filter((item) => item.status === "Pending").length} pending · ${applications.length} total`} headers={["Community", "Campaign", "Platform", "Status", "Applied"]} rows={applications.map((application) => [<strong>{application.community}</strong>, application.campaign, application.platform, statusPill(application.status), application.applied])} /></AdminShell>; }
export function AdminPlacementsPage() { const { applications, clicks } = useAdminMarketplace(); const placements = applications.filter((application) => application.status === "Accepted"); return <AdminShell title="Placements" subtitle="Monitor accepted communities and delivery"><TablePanel title={`${placements.length} accepted placements`} headers={["Community", "Campaign", "Status", "Clicks", "Earnings"]} rows={placements.map((placement) => { const qualified = clicks.filter((event) => event.placementId === placement.id && event.qualification === "Qualified").length; return [<strong>{placement.community}</strong>, placement.campaign, statusPill(placement.placementStatus ?? "Ready to Post"), qualified.toLocaleString(), formatMoney(qualified * Number(placement.communityOwnerCpc.replace(/[^0-9.]/g, "")))]; })} /></AdminShell>; }
export function AdminCommunitiesPage() { const { communities, applications, clicks } = useAdminMarketplace(); return <AdminShell title="Communities" subtitle="Review community inventory, verification, and delivery performance"><TablePanel title={`${communities.length} registered communities`} headers={["Community", "Platform", "Audience", "Verification", "Applications", "Clicks"]} rows={communities.map((community) => [<strong>{community.name}</strong>, community.platform, community.members, statusPill(community.verification), applications.filter((item) => item.communityId === community.id).length, clicks.filter((event) => event.communityId === community.id && event.qualification === "Qualified").length.toLocaleString()])} /></AdminShell>; }
export function AdminFinancialsPage() { const { campaigns, clicks, applications } = useAdminMarketplace(); const totals = campaigns.reduce((sum, campaign) => { const financials = campaignFinancials(campaign, clicks); return { spend: sum.spend + financials.advertiserSpend, owner: sum.owner + financials.communityOwnerEarnings, fee: sum.fee + financials.platformRevenue }; }, { spend: 0, owner: 0, fee: 0 }); return <AdminShell title="Financials" subtitle="See CPC spend, Community Owner earnings, and platform fee totals"><section className="admin-react-stats"><div><small>Advertiser spend</small><strong>{formatMoney(totals.spend)}</strong><em>{clicks.filter((event) => event.qualification === "Qualified").length.toLocaleString()} qualified clicks</em></div><div><small>Community earnings</small><strong>{formatMoney(totals.owner)}</strong><em>75% payout share</em></div><div><small>Platform revenue</small><strong>{formatMoney(totals.fee)}</strong><em>25% platform fee</em></div><div><small>Committed placements</small><strong>{applications.filter((item) => item.status === "Accepted").length}</strong><em>accepted records</em></div></section><TablePanel title="Campaign financial ledger" headers={["Campaign", "Budget", "Spend", "Remaining", "Platform fee"]} rows={campaigns.map((campaign) => { const financials = campaignFinancials(campaign, clicks); return [<strong>{campaign.name}</strong>, campaign.budget, formatMoney(financials.advertiserSpend), formatMoney(financials.remainingBudget), formatMoney(financials.platformRevenue)]; })} /></AdminShell>; }
export function AdminActivityPage() { const { activities } = useAdminMarketplace(); return <AdminShell title="Activity" subtitle="A chronological record of platform movement"><section className="admin-react-panel"><div className="admin-react-panel-heading"><h2>{activities.length} lifecycle events</h2><span className="admin-react-pill blue">Persisted history</span></div>{activities.length ? activities.map((item) => <div className="admin-react-activity" key={item.id}><span>↗</span><div><strong>{item.event}</strong><small>{item.campaignName} · {new Date(item.timestamp).toLocaleString()}</small></div></div>) : <div className="admin-react-empty">No campaign lifecycle events have been recorded yet.</div>}</section></AdminShell>; }
export function AdminSettingsPage() { return <AdminShell title="Settings" subtitle="Configure the independent admin workspace"><div className="admin-react-two-column"><section className="admin-react-panel"><div className="admin-react-panel-heading"><h2>Admin profile</h2></div><label>Display name<input value="Admin Director" readOnly /></label><label>Admin email<input value="admin@relay.local" readOnly /></label><button className="admin-react-primary" type="button">Save profile <span>→</span></button></section><section className="admin-react-panel"><div className="admin-react-panel-heading"><h2>Access boundary</h2></div><p>This portal is frontend-only and intentionally separate from marketplace user authentication.</p><span className="admin-react-pill green">Separate admin root enabled</span></section></div></AdminShell>; }
