import { useEffect, useMemo, useState } from "react";
import { Building2, BriefcaseBusiness, ClipboardList, Search, ShieldCheck, Users, X } from "lucide-react";
import { Link } from "wouter";
import AdminState from "./AdminState";
import { communities, getClickEvents, readApplications, readCampaigns } from "@/data/marketplaceData";
import type { MarketplaceApplication } from "@/data/marketplaceData";

type SearchType = "Users" | "Campaigns" | "Communities" | "Applications" | "Placements";
type SearchResult = { id: string; type: SearchType; title: string; meta: string; detail: string; href: string };
const groupOrder: SearchType[] = ["Users", "Campaigns", "Communities", "Applications", "Placements"];
const groupIcons = { Users, Campaigns: BriefcaseBusiness, Communities: Building2, Applications: ClipboardList, Placements: ShieldCheck };
function ownerLabel(value?: string) { return value ? value.replaceAll("-", " ") : "Unknown owner"; }
function placementStatus(application: MarketplaceApplication) { return application.placementStatus ?? "Ready to Post"; }
function buildResults(): SearchResult[] { const campaigns = readCampaigns(); const applications = readApplications(); const clicks = getClickEvents(); const advertisers = Array.from(new Set(campaigns.map((campaign) => campaign.advertiser))); const owners = Array.from(new Set(communities.map((community) => community.ownerId))); const users: SearchResult[] = [...advertisers.map((advertiser) => ({ id: `advertiser-${advertiser}`, type: "Users" as const, title: advertiser, meta: "Advertiser", detail: `${campaigns.filter((campaign) => campaign.advertiser === advertiser).length} campaigns`, href: "/admin/users" })), ...owners.map((owner) => ({ id: `owner-${owner}`, type: "Users" as const, title: ownerLabel(owner), meta: "Community Owner", detail: `${communities.filter((community) => community.ownerId === owner).length} communities`, href: "/admin/users" }))]; const campaignResults = campaigns.map((campaign) => ({ id: campaign.id, type: "Campaigns" as const, title: campaign.name, meta: campaign.advertiser, detail: `${campaign.status} · ${campaign.category}`, href: "/admin/campaigns" })); const communityResults = communities.map((community) => ({ id: community.id, type: "Communities" as const, title: community.name, meta: ownerLabel(community.ownerId), detail: `${community.platform} · ${community.members} members`, href: "/admin/communities" })); const applicationResults = applications.map((application) => ({ id: application.id, type: "Applications" as const, title: application.community, meta: application.campaign, detail: `${application.status} · ${application.platform}`, href: "/admin/applications" })); const accepted = applications.filter((application) => application.status === "Accepted"); const placementResults = accepted.map((application) => ({ id: `placement-${application.id}`, type: "Placements" as const, title: application.community, meta: application.campaign, detail: `${placementStatus(application)} · ${clicks.filter((click) => click.placementId === application.id && click.qualification === "Qualified").length} qualified clicks`, href: "/admin/placements" })); return [...users, ...campaignResults, ...communityResults, ...applicationResults, ...placementResults]; }

export default function AdminGlobalSearch() {
  const [query, setQuery] = useState("");
  const [open, setOpen] = useState(false);
  const [version, setVersion] = useState(0);
  useEffect(() => { const refresh = () => setVersion((value) => value + 1); const events = ["storage", "ownerboard:applications-updated", "ownerboard:click-events-updated", "ownerboard:campaigns-updated"]; events.forEach((event) => window.addEventListener(event, refresh)); const keydown = (event: KeyboardEvent) => { if (event.key === "Escape") { setOpen(false); setQuery(""); } }; window.addEventListener("keydown", keydown); return () => { events.forEach((event) => window.removeEventListener(event, refresh)); window.removeEventListener("keydown", keydown); }; }, []);
  const results = useMemo(() => { void version; const normalized = query.trim().toLowerCase(); if (!normalized) return []; return buildResults().filter((result) => `${result.title} ${result.meta} ${result.detail}`.toLowerCase().includes(normalized)); }, [query, version]);
  const grouped = groupOrder.map((type) => ({ type, results: results.filter((result) => result.type === type) })).filter((group) => group.results.length);
  return <div className="admin-react-search-wrap"><Search size={15} /><input aria-label="Search Admin marketplace" placeholder="Search marketplace" value={query} onFocus={() => setOpen(true)} onChange={(event) => { setQuery(event.target.value); setOpen(true); }} />{query && <button type="button" aria-label="Clear Admin marketplace search" onClick={() => { setQuery(""); setOpen(false); }}><X size={13} /></button>}{open && query.trim() && <div className="admin-global-search-results">{grouped.length ? grouped.map((group) => { const Icon = groupIcons[group.type]; return <section key={group.type}><h4><Icon size={12} />{group.type}<span>{group.results.length}</span></h4>{group.results.slice(0, 5).map((result) => <Link key={result.id} href={result.href} onClick={() => { setOpen(false); setQuery(""); }}><span className="admin-global-search-result-icon"><Icon size={13} /></span><span><strong>{result.title}</strong><small>{result.meta} · {result.detail}</small></span></Link>)}</section>; }) : <AdminState kind="search" title="No marketplace records found" description="Try a user, campaign, community, application, or placement name." compact />}</div>}</div>;
}
